import type { Config } from "tailwindcss"

const config = {
  darkMode: "class",
  content: [
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#5ddeca",
        "surface-dim": "#c7dde9",
        "surface": "#f3faff",
        "tertiary": "#00463e",
        "primary": "#004357",
        "primary-container": "#1a5c72",
        "on-surface-variant": "#40484e",
        "on-tertiary-fixed-variant": "#005047",
        "on-secondary-fixed": "#001f23",
        "surface-container": "#dbf1fe",
        "tertiary-fixed": "#79f7e3",
        "on-secondary": "#ffffff",
        "secondary": "#006972",
        "surface-container-high": "#d5ecf8",
        "outline": "#70787e",
        "on-secondary-container": "#006d77",
        "on-primary-container": "#98d2ec",
        "tertiary-fixed-dim": "#59dbc7",
        "secondary-fixed": "#92f1fe",
        "primary-fixed": "#bce9ff",
        "surface-container-low": "#e6f6ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#1e333c",
        "surface-container-highest": "#cfe6f2",
        "on-tertiary-fixed": "#00201c",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#75d5e2",
        "surface-variant": "#cfe6f2",
        "on-background": "#071e27",
        "secondary-container": "#8feefc",
        "surface-tint": "#27657c",
        "on-secondary-fixed-variant": "#004f56",
        "primary-fixed-dim": "#95cfe9",
        "on-primary-fixed-variant": "#004d63",
        "outline-variant": "#c0c7ce",
        "inverse-on-surface": "#dff4ff",
        "tertiary-container": "#006055",
        "inverse-primary": "#95cfe9",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001f29",
        "surface-bright": "#f3faff",
        "on-surface": "#071e27",
        "background": "#f3faff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        label: ["var(--font-body)", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
