import { Announcement } from '@/lib/types/announcement';

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Pembersihan Lingkungan Bersama',
    content: 'Kami akan mengadakan pembersihan lingkungan bersama pada hari Minggu, 24 Maret 2024 pukul 07:00 di lapangan RT. Mohon partisipasi seluruh anggota keluarga untuk menjaga kebersihan lingkungan kita.',
    isPinned: true,
    tags: ['kegiatan', 'umum'],
    createdBy: 'Sekretaris',
    createdAt: new Date('2024-03-22'),
    updatedAt: new Date('2024-03-22'),
  },
  {
    id: '2',
    title: 'Pengumuman Penyesuaian Iuran RT',
    content: 'Berdasarkan rapat RT tanggal 20 Maret 2024, telah disepakati kenaikan iuran RT sebesar 10% mulai bulan April 2024. Peningkatan ini untuk meningkatkan kualitas layanan dan pemeliharaan fasilitas umum.',
    isPinned: true,
    tags: ['keuangan', 'penting'],
    createdBy: 'Ketua RT',
    createdAt: new Date('2024-03-21'),
    updatedAt: new Date('2024-03-21'),
  },
  {
    id: '3',
    title: 'Pemeriksaan Kesehatan Gratis',
    content: 'Puskesmas Kesehatan akan mengadakan pemeriksaan kesehatan gratis untuk seluruh warga RT kami pada tanggal 26 Maret 2024. Pemeriksaan mencakup tekanan darah, gula darah, dan konsultasi umum.',
    isPinned: false,
    tags: ['kesehatan'],
    createdBy: 'Sekretaris',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '4',
    title: 'Rapat Rutin Bulan Maret',
    content: 'Rapat rutin bulanan RT akan dilaksanakan pada hari Jumat, 29 Maret 2024 pukul 19:00 di rumah ketua RT. Agenda: evaluasi kegiatan bulan Maret, pembahasan iuran, dan rencana kegiatan April.',
    isPinned: false,
    tags: ['rapat', 'penting'],
    createdBy: 'Ketua RT',
    createdAt: new Date('2024-03-19'),
    updatedAt: new Date('2024-03-19'),
  },
  {
    id: '5',
    title: 'Perbaikan Jalan Lingkungan',
    content: 'Tim maintenance akan melakukan perbaikan jalan di blok A-D mulai tanggal 25 Maret 2024. Mohon parkir kendaraan di area yang aman. Estimasi perbaikan selesai dalam 3 hari.',
    isPinned: false,
    tags: ['pemeliharaan'],
    createdBy: 'Wakil RT',
    createdAt: new Date('2024-03-18'),
    updatedAt: new Date('2024-03-18'),
  },
];
