import { Member, MembersStats } from '@/lib/types/member';

export const mockMembers: Member[] = [
  {
    id: '1',
    kkNumber: '3273011234567890',
    familyHeadName: 'Budi Santoso',
    address: 'Blok A',
    houseNumber: '15',
    ownershipStatus: 'milik',
    totalFamilyMembers: 4,
    phoneNumber: '+62812345678',
    status: 'aktif',
    email: 'budi@example.com',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-03-20'),
    members: [
      { id: '1-1', name: 'Budi Santoso', relationship: 'Suami', age: 45 },
      { id: '1-2', name: 'Siti Nurhaliza', relationship: 'Istri', age: 42 },
      { id: '1-3', name: 'Ahmad Santoso', relationship: 'Anak', age: 18 },
      { id: '1-4', name: 'Dina Santoso', relationship: 'Anak', age: 15 },
    ],
  },
  {
    id: '2',
    kkNumber: '3273011234567891',
    familyHeadName: 'Rudi Hartono',
    address: 'Blok B',
    houseNumber: '23',
    ownershipStatus: 'sewa',
    totalFamilyMembers: 3,
    phoneNumber: '+62823456789',
    status: 'aktif',
    email: 'rudi@example.com',
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2024-02-15'),
    members: [
      { id: '2-1', name: 'Rudi Hartono', relationship: 'Suami', age: 38 },
      { id: '2-2', name: 'Ani Hartono', relationship: 'Istri', age: 35 },
      { id: '2-3', name: 'Rina Hartono', relationship: 'Anak', age: 12 },
    ],
  },
  {
    id: '3',
    kkNumber: '3273011234567892',
    familyHeadName: 'Joko Widodo',
    address: 'Blok C',
    houseNumber: '8',
    ownershipStatus: 'milik',
    totalFamilyMembers: 5,
    phoneNumber: '+62834567890',
    status: 'aktif',
    email: 'joko@example.com',
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2024-01-10'),
    members: [
      { id: '3-1', name: 'Joko Widodo', relationship: 'Suami', age: 52 },
      { id: '3-2', name: 'Lily Widodo', relationship: 'Istri', age: 50 },
      { id: '3-3', name: 'Bambang Widodo', relationship: 'Anak', age: 25 },
      { id: '3-4', name: 'Sinta Widodo', relationship: 'Anak', age: 22 },
      { id: '3-5', name: 'Tini Widodo', relationship: 'Anak', age: 19 },
    ],
  },
  {
    id: '4',
    kkNumber: '3273011234567893',
    familyHeadName: 'Hendra Kusuma',
    address: 'Blok D',
    houseNumber: '12',
    ownershipStatus: 'sewa',
    totalFamilyMembers: 2,
    phoneNumber: '+62845678901',
    status: 'aktif',
    email: 'hendra@example.com',
    createdAt: new Date('2023-04-20'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '5',
    kkNumber: '3273011234567894',
    familyHeadName: 'Sinta Wijaya',
    address: 'Blok E',
    houseNumber: '30',
    ownershipStatus: 'milik',
    totalFamilyMembers: 3,
    phoneNumber: '+62856789012',
    status: 'nonaktif',
    email: 'sinta@example.com',
    createdAt: new Date('2023-05-10'),
    updatedAt: new Date('2023-12-15'),
  },
];

export const mockMembersStats: MembersStats = {
  totalKK: 142,
  totalWarga: 518,
  hunianMilik: 94,
  hunianSewa: 48,
  aktif: 130,
  nonaktif: 12,
};
